apiVersion: 1.0.0
metadata:
  generateName: twas
attributes:
  odo.autorestart: "false"
projects:
- name: twas
  source:
    type: git
    location: https://github.com/gmarcy/twasTemplate.git
components:
- type: chePlugin
  id: redhat/java/latest
  memoryLimit: 1512Mi
- alias: devruntime
  mountSources: true
  type: dockerimage
  image: gmarcy/twas-dev:latest
  memoryLimit: 768Mi
  volumes:
  - name: m2
    containerPath: /home/user/.m2
  endpoints:
  - name: 9080/tcp
    port: 9080
  - name: 9443/tcp
    port: 9443
commands:
- actions:
  - command: /artifacts/bin/build.sh
    component: devruntime
    type: exec
    workdir: /projects/twas
  name: devBuild
- actions:
  - command: /artifacts/bin/run.sh
    component: devruntime
    type: exec
    workdir: /projects/twas
  name: devRun
